"""add occurred_date to incidents

Revision ID: f8850e3bdf8a
Revises: 8bb7d78cdf9a
Create Date: 2026-05-16 21:56:06.962547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8850e3bdf8a'
down_revision: Union[str, Sequence[str], None] = '8bb7d78cdf9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.add_column('incidents', sa.Column('occurred_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'occurred_date')
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('sources_incident_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sources_pkey'))
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    # ### end Alembic commands ###
